### ISSUE TITLE
Not open console

### ISSUE THREAD

**Issue by Obka** [eschutz/atom-console#4]
Hello
after install this package i can't open the console with ctrl+alt+x .
my atom version is 1.29.0 X64 how can i do ?
Thank

**Comment by eschutz** [comment]
Hi,
What happens if you type `atom-console:toggle` into the command palette?
Also, what UI and syntax themes are you using?

**Comment by Obka** [comment]
not happen ,
i use default ui and php syntax

**Comment by eschutz** [comment]
Could you try again with the developer console open? `alt-cmd-i` Please print any logs or errors here if they appear.

**Comment by Obka** [comment]
in console not log for atom-console
see this pictures when i press ctrl+alt+x a things open bottom of page but i can't see it can you see and understand what say ?

![1](https://user-images.githubusercontent.com/13798815/44001380-3c1f272c-9e46-11e8-878c-c6427cf0ebe9.gif)

**Comment by eschutz** [comment]
Those don't appear to be the default UI/Syntax themes. Under Settings > Themes it will say what you have enabled.
I can reproduce the bug with Atom Material UI, which looks very similar.

**Comment by eschutz** [comment]
@Obka I've pushed an update that mostly fixes the issue on Atom Material UI. There's still an issue with indentation and line height, but it is usable for now. Feel free to submit a pull request if you find a fix for it!
Please let me know if this fixed the issue.

**Comment by Obka** [comment]
oh yes that's fixed 
thank you so much

**Comment by eschutz** [comment]
You're welcome!
